export const GLOSSARY_TERMS: { term: string; definition: string; module: string }[] = [
    { term: 'ABAP', definition: 'Advanced Business Application Programming. The proprietary, high-level programming language created by SAP for developing applications on the SAP platform.', module: 'ABAP' },
    { term: 'ACDOCA', definition: 'The Universal Journal. The single table for all financial and controlling line items in S/4HANA, unifying FI and CO.', module: 'FICO' },
    { term: 'Activate Methodology', definition: 'The modern, agile methodology used for S/4HANA implementations, replacing the older ASAP methodology.', module: 'General' },
    { term: 'ALE', definition: 'Application Link Enabling. The technology used to set up the distribution model for exchanging IDocs between SAP systems.', module: 'ABAP' },
    { term: 'ALV', definition: 'ABAP List Viewer. A powerful and flexible framework provided by SAP to display data in a standardized grid or list format with built-in functions like sorting and filtering.', module: 'ABAP' },
    { term: 'AMDP', definition: 'ABAP Managed Database Procedures. A framework that allows developers to write and execute database procedures (using native SQLScript) within ABAP methods.', module: 'ABAP' },
    { term: 'APP', definition: 'Automatic Payment Program. A tool that automates the process of making payments to vendors in bulk.', module: 'FICO' },
    { term: 'ASAP Methodology', definition: 'Accelerated SAP. The traditional, waterfall-based implementation methodology for SAP ECC.', module: 'General' },
    { term: 'ATC', definition: 'ABAP Test Cockpit. The central framework for static code analysis, used to check custom code for quality, performance, and S/4HANA readiness.', module: 'ABAP' },
    { term: 'ATP', definition: 'Available-to-Promise. A function that checks in real-time if a requested material will be available on a requested delivery date.', module: 'SD' },
    { term: 'aATP', definition: 'Advanced Available-to-Promise. The next-generation availability check in S/4HANA, offering more powerful features like backorder processing and product allocation.', module: 'SD' },
    { term: 'BAdI', definition: 'Business Add-In. An object-oriented enhancement technique that allows developers to add custom logic to standard SAP programs at predefined "hooks".', module: 'ABAP' },
    { term: 'BAPI', definition: 'Business Application Programming Interface. A standardized, remote-enabled function module that provides a stable interface to SAP business objects (e.g., Sales Order).', module: 'ABAP' },
    { term: 'Batch Management', definition: 'A system for managing and tracking materials that are produced or procured in discrete quantities or "batches," crucial for traceability.', module: 'MM' },
    { term: 'BP (Business Partner)', definition: 'The single, mandatory point of entry for maintaining customer and vendor master data in S/4HANA.', module: 'General' },
    { term: 'BRF+', definition: 'Business Rule Framework plus. The new, recommended technology for output management in S/4HANA, replacing the classic NACE/condition technique.', module: 'General' },
    { term: 'CDS View', definition: 'Core Data Services View. The modern way of data modeling in S/4HANA, allowing the definition of semantically rich data models that are executed on the HANA database.', module: 'ABAP' },
    { term: 'Chart of Accounts', definition: 'A structured list of all General Ledger (G/L) accounts used by one or more company codes.', module: 'FICO' },
    { term: 'CO-PA', definition: 'Profitability Analysis. A sub-module of Controlling designed to analyze the profitability of market segments.', module: 'FICO' },
    { term: 'Code-to-Data', definition: 'The modern programming paradigm for HANA, where data-intensive calculations are pushed from the application layer down to the database to leverage its power.', module: 'ABAP' },
    { term: 'Company Code', definition: 'The smallest organizational unit for which a complete, self-contained set of accounts can be created for external reporting.', module: 'FICO' },
    { term: 'Condition Technique', definition: 'A flexible method used in SAP to determine results like pricing, output, and account determination by searching for valid master data records.', module: 'General' },
    { term: 'Controlling Area', definition: 'The central organizational unit in Controlling (CO), where costs and revenues are managed.', module: 'FICO' },
    { term: 'Cost Center', definition: 'An organizational unit (e.g., a department) where costs are incurred and tracked.', module: 'FICO' },
    { term: 'Credit Management (FSCM)', definition: 'The S/4HANA module for managing customer credit risk, replacing the classic SD credit management.', module: 'SD' },
    { term: 'CTS', definition: 'Change and Transport System. The tool used for moving development objects and configuration from the development system to subsequent systems (QA, Production).', module: 'ABAP' },
    { term: 'CVI', definition: 'Customer-Vendor Integration. The framework that synchronizes the Business Partner object with the underlying customer and vendor tables.', module: 'General' },
    { term: 'Document Splitting', definition: 'A key feature of the New G/L (and S/4HANA) that automatically splits document line items to ensure balanced financial statements for entities like profit centers or segments.', module: 'FICO' },
    { term: 'Dunning', definition: 'The process of systematically reminding customers of their overdue invoices.', module: 'FICO' },
    { term: 'EDI', definition: 'Electronic Data Interchange. A standard for exchanging business documents (like POs and invoices) electronically between companies.', module: 'General' },
    { term: 'Enhancement', definition: 'A way to add custom functionality to a standard SAP program without changing the original object, preferred over modification.', module: 'ABAP' },
    { term: 'ERP', definition: 'Enterprise Resource Planning. Software that integrates the key business functions of an organization into a single, centralized system.', module: 'General' },
    { term: 'EWM', definition: 'Extended Warehouse Management. SAP\'s strategic and advanced solution for managing warehouse logistics, embedded in S/4HANA.', module: 'SD' },
    { term: 'Fiori', definition: 'SAP\'s modern, role-based user experience (UX) for S/4HANA, composed of apps on a launchpad.', module: 'General' },
    { term: 'FSV', definition: 'Financial Statement Version. A hierarchical structure that defines how G/L accounts are grouped and displayed in financial statements.', module: 'FICO' },
    { term: 'GR/IR', definition: 'Goods Receipt / Invoice Receipt. A clearing account used in the P2P process to buffer the timing difference between receiving goods and receiving the invoice.', module: 'MM' },
    { term: 'IDoc', definition: 'Intermediate Document. A standard SAP data container for exchanging business information between systems, often used for EDI and ALE.', module: 'ABAP' },
    { term: 'Internal Order', definition: 'A short-lived cost object used to plan, collect, and analyze the costs of a specific job or event.', module: 'FICO' },
    { term: 'Lockbox', definition: 'A service offered by banks to automate the processing of customer payments received by mail.', module: 'FICO' },
    { term: 'LSMW', definition: 'Legacy System Migration Workbench. A traditional tool for migrating data into SAP, now largely superseded by the S/4HANA Migration Cockpit.', module: 'General' },
    { term: 'LTMC', definition: 'Legacy to Migration Cockpit (S/4HANA Migration Cockpit). The recommended tool for data migration into S/4HANA.', module: 'General' },
    { term: 'Material Ledger', definition: 'A component that is mandatory in S/4HANA, used for actual costing and parallel currency valuation of materials.', module: 'MM' },
    { term: 'MIRO', definition: 'The transaction code for Logistics Invoice Verification, used to post a vendor invoice against a purchase order.', module: 'MM' },
    { term: 'Modification', definition: 'A direct change to a standard SAP object, which is discouraged because it can be overwritten during upgrades.', module: 'ABAP' },
    { term: 'MRP', definition: 'Material Requirements Planning. A planning tool that calculates material needs and generates procurement proposals.', module: 'MM' },
    { term: 'NACE', definition: 'The classic transaction code for configuring output (message) determination using the condition technique.', module: 'General' },
    { term: 'OBYC', definition: 'The transaction code for configuring MM-FI automatic account determination, linking material movements to G/L accounts.', module: 'MM' },
    { term: 'OData', definition: 'Open Data Protocol. A standard web protocol for building and consuming RESTful APIs, used as the communication channel between Fiori apps and the S/4HANA backend.', module: 'ABAP' },
    { term: 'Order-to-Cash (O2C)', definition: 'The end-to-end business process managed by SAP SD, covering all activities from receiving a customer order to receiving payment.', module: 'SD' },
    { term: 'P2P', definition: 'Procure-to-Pay. The end-to-end business process managed by SAP MM, covering all activities from creating a purchase requisition to paying the vendor.', module: 'MM' },
    { term: 'Partner Function', definition: 'Describes the roles a Business Partner can play in a sales transaction (e.g., Sold-to, Ship-to, Bill-to, Payer).', module: 'SD' },
    { term: 'PGI', definition: 'Post Goods Issue. The final step in shipping that signifies the legal transfer of ownership and triggers the COGS financial posting.', module: 'SD' },
    { term: 'Plant', definition: 'An operational unit where goods are produced, stored, or distributed. It is the level at which material valuation occurs.', module: 'MM' },
    { term: 'Procure-to-Pay (P2P)', definition: 'The end-to-end business process managed by SAP MM, covering all activities from creating a purchase requisition to paying the vendor.', module: 'MM' },
    { term: 'Profit Center', definition: 'An organizational unit used to analyze both costs and revenues to evaluate the profit or loss of an internal area of responsibility.', module: 'FICO' },
    { term: 'Purchasing Organization', definition: 'An organizational unit responsible for procuring materials and negotiating purchasing conditions with vendors.', module: 'MM' },
    { term: 'RAP', definition: 'ABAP RESTful Application Programming Model. The modern, strategic programming model in S/4HANA for building Fiori-based applications and OData services.', module: 'ABAP' },
    { term: 'RFC', definition: 'Remote Function Call. The standard SAP interface for communication between SAP systems, allowing a program to execute a function module in a remote system.', module: 'ABAP' },
    { term: 'Sales Area', definition: 'A unique combination of Sales Organization, Distribution Channel, and Division that defines the sales strategy and structure.', module: 'SD' },
    { term: 'Settlement Management', definition: 'The S/4HANA solution for managing customer and supplier rebates, replacing classic SD Rebate functionality.', module: 'SD' },
    { term: 'SPRO', definition: 'SAP Project Reference Object. The transaction used to access the IMG (Implementation Guide) for system configuration.', module: 'General' },
    { term: 'STO', definition: 'Stock Transport Order. A formal process for transferring materials from one plant to another within a company.', module: 'MM' },
    { term: 'T-Code', definition: 'Transaction Code. A short code used to launch a specific task or program in the SAP GUI.', module: 'General' },
    { term: 'Universal Journal', definition: 'Also known as ACDOCA, this is the single source of truth for all financial and controlling data in S/4HANA.', module: 'FICO' },
    { term: 'Validation', definition: 'A rule that checks entered data against a condition and issues an error or warning message if the condition is not met.', module: 'FICO' },
    { term: 'VKOA', definition: 'The transaction code for configuring SD-FI revenue account determination.', module: 'SD' },
    { term: 'WM', definition: 'Warehouse Management. The classic SAP module for managing warehouse logistics, now largely superseded by EWM in S/4HANA.', module: 'SD' }
].sort((a, b) => a.term.localeCompare(b.term));
