import type { Chapter } from '../../../types';

export const CHAPTER_10_MRP: Chapter = {
  id: 'ch10',
  title: '10. Material Requirements Planning (MRP)',
  lessons: [
    {
      id: 'l10-1',
      title: 'MRP Overview',
      duration: 15,
      details: {
        definition: 'MRP is a planning tool that calculates material requirements and generates procurement proposals to meet demand while considering current stock levels.',
        purpose: 'To ensure material availability, avoid shortages, and plan procurement activities automatically.',
        updatesS4HANA: 'S/4HANA introduces MRP Live (MD01N), which is a new, performance-optimized MRP run that takes advantage of the HANA in-memory database to run much faster than classic MRP.',
      },
    },
    {
      id: 'l10-2',
      title: 'MRP Master Data (MRP Views)',
      duration: 20,
      details: {
        definition: 'The behavior of a material in the MRP run is controlled by parameters set in the four MRP views of the Material Master.',
        purpose: 'To define how a material is planned. Key fields include MRP Type (e.g., PD for MRP, VB for Reorder Point), Lot Size, and Procurement Type (in-house production or external procurement).',
        updatesS4HANA: 'These views are still the core of MRP configuration.',
      },
    },
    {
      id: 'l10-3',
      title: 'MRP Run & Evaluation',
      duration: 15,
      details: {
        tCode: 'MD01N (MRP Live), MD04 (Stock/Requirements List)',
        definition: 'The MRP run executes the planning calculation. The Stock/Requirements List is the primary tool to view the results, showing all demands, supplies, and the procurement proposals generated by MRP.',
        purpose: 'To execute the planning process and analyze the results.',
        updatesS4HANA: 'MRP Live is the strategic planning tool. MD04 remains the essential tool for evaluating the planning situation for a single material.',
      },
    },
  ],
  quiz: {
    id: 'mm-q10',
    title: 'MRP Quiz',
    questions: [
      { question: 'What is the new, performance-optimized MRP transaction in S/4HANA?', options: ['MD01', 'MD02', 'MD01N'], correctAnswer: 2 },
      { question: 'Which transaction is used to view the planning results for a single material?', options: ['MD04', 'MM01', 'ME21N'], correctAnswer: 0 },
      { question: 'The MRP parameters for a material are maintained in which master data object?', options: ['Vendor Master', 'Material Master', 'Info Record'], correctAnswer: 1 },
    ]
  }
};
