import type { Chapter } from '../../../types';

export const CHAPTER_2_ORG_STRUCTURE: Chapter = {
  id: 'ch2',
  title: '2. Organization Structure in Finance',
  lessons: [
    {
      id: 'l2-1',
      title: 'Define Company',
      duration: 10,
      details: {
        tCode: 'OX15',
        sproPath: 'Enterprise Structure > Definition > Financial Accounting > Define Company',
        definition: 'A Company is the highest organizational unit in SAP, used for legal consolidation. It represents a business group and can consist of one or more company codes.',
        purpose: 'To create consolidated financial statements at the group level, as required by law. It is a 6-character alphanumeric key.',
        configurationSteps: ['Enter a 6-digit ID, Company Name, and address details.'],
        integrationNotes: 'This unit is primarily for consolidation in the FI-LC module or other consolidation tools. Day-to-day transactions are not posted at the Company level.',
        updatesS4HANA: 'The concept and configuration of a Company remain the same in S/4HANA.',
      },
    },
    {
      id: 'l2-2',
      title: 'Define Company Code',
      duration: 15,
      details: {
        tCode: 'OX02',
        sproPath: 'Enterprise Structure > Definition > Financial Accounting > Edit, Copy, Delete, Check Company Code',
        definition: 'A Company Code is the smallest and most central organizational unit for which a complete, self-contained set of accounts can be created for external reporting purposes.',
        purpose: 'To generate legally required financial statements like the Balance Sheet and P&L statement. It is a 4-character alphanumeric key.',
        configurationSteps: ['Create a 4-digit ID, provide Company Name, City, Country, Currency, and Language.'],
        integrationNotes: 'All operational postings in FI and other modules occur at the Company Code level. It is a mandatory organizational unit for implementing Financial Accounting.',
        updatesS4HANA: 'The concept and configuration of a Company Code remain the same in S/4HANA.',
      },
    },
    {
      id: 'l2-3',
      title: 'Assign Company Code to Company',
      duration: 5,
      details: {
        tCode: 'OX16',
        sproPath: 'Enterprise Structure > Assignment > Financial Accounting > Assign company code to company',
        definition: 'This step creates a many-to-one link between one or more Company Codes and a single Company.',
        purpose: 'To establish the group structure for consolidation. This assignment makes it possible to roll up the financial data from the company codes to the parent company.',
        configurationSteps: ['Select your Company Code and assign it to your defined Company ID.'],
        integrationNotes: 'This link is crucial for legal consolidation processes.',
        updatesS4HANA: 'This assignment logic is unchanged in S/4HANA.',
      },
    },
    {
      id: 'l2-4',
      title: 'Define Business Areas',
      duration: 10,
      details: {
        tCode: 'OX03',
        sproPath: 'Enterprise Structure > Definition > Financial Accounting > Define Business Area',
        definition: 'A Business Area is an organizational unit that represents a separate area of operations or responsibility within an organization, used for internal reporting across company codes.',
        purpose: 'To generate internal financial statements for different business segments or divisions (e.g., product lines, geographical locations).',
        configurationSteps: ['Define a 4-character key and description for each business area.'],
        integrationNotes: 'Business Areas are independent of company codes and can be used to create reports that span multiple legal entities.',
        updatesS4HANA: 'Business Areas are still supported, but the best practice in S/4HANA is to use Profit Centers and Segments for this type of reporting, as they are fully integrated into the Universal Journal and offer more robust functionality.',
      },
    },
    {
      id: 'l2-5',
      title: 'Define Fiscal Year Variants',
      duration: 15,
      details: {
        tCode: 'OB29',
        sproPath: 'Financial Accounting > Financial Accounting Global Settings > Ledgers > Fiscal Year and Posting Periods > Maintain Fiscal Year Variant',
        definition: 'A Fiscal Year Variant defines the posting periods and special periods that make up a fiscal year. It can be calendar year (e.g., Jan-Dec) or non-calendar year (e.g., Apr-Mar).',
        purpose: 'To structure the fiscal year according to a company\'s financial reporting schedule. It is a mandatory setting for a company code.',
        configurationSteps: ['Define a 2-character variant. Specify the number of posting periods (e.g., 12) and special periods (e.g., 4 for year-end adjustments).'],
        integrationNotes: 'This variant controls the period in which a transaction is posted based on its posting date.',
        updatesS4HANA: 'The configuration and purpose of Fiscal Year Variants are the same in S/4HANA.',
      },
    },
    {
      id: 'l2-6',
      title: 'Assign Fiscal Year Variant to Company Code',
      duration: 5,
      details: {
        tCode: 'OB37',
        sproPath: 'Financial Accounting > Financial Accounting Global Settings > Ledgers > Fiscal Year and Posting Periods > Assign Company Code to a Fiscal Year Variant',
        definition: 'This step links a company code to a specific Fiscal Year Variant.',
        purpose: 'To ensure all postings within a company code adhere to the defined fiscal year structure.',
        configurationSteps: ['Select your company code and assign the 2-character Fiscal Year Variant to it.'],
        integrationNotes: 'A single Fiscal Year Variant can be assigned to multiple company codes.',
        updatesS4HANA: 'This assignment logic is unchanged in S/4HANA.',
      },
    },
    {
      id: 'l2-7',
      title: 'Define Posting Period Variants',
      duration: 10,
      details: {
        tCode: 'OBBO',
        sproPath: 'Financial Accounting > Financial Accounting Global Settings > Ledgers > Fiscal Year and Posting Periods > Posting Periods > Define Variants for Open Posting Periods',
        definition: 'A Posting Period Variant is a key that groups multiple company codes together for the purpose of opening and closing posting periods.',
        purpose: 'To control which accounting periods are open for posting, preventing users from posting documents to incorrect periods. This simplifies period-end closing.',
        configurationSteps: ['Define a 4-character variant and a description.'],
        integrationNotes: 'It is a best practice to create one variant per company code, e.g., using the same ID as the company code, unless multiple company codes always have the same period-end closing schedule.',
        updatesS4HANA: 'Configuration remains the same. However, with the Universal Journal, it\'s also necessary to manage periods for CO postings (T-Code OKP1).',
      },
    },
    {
      id: 'l2-8',
      title: 'Open and Close Posting Periods',
      duration: 15,
      details: {
        tCode: 'OB52',
        sproPath: 'Financial Accounting > Financial Accounting Global Settings > Ledgers > Fiscal Year and Posting Periods > Posting Periods > Open and Close Posting Periods',
        definition: 'This is the configuration where you specify which posting periods are open for posting for different account types (+, A, D, K, M, S).',
        purpose: 'To maintain strict control over the financial closing process. Typically, only the current period is open, and past periods are closed after month-end closing activities are complete.',
        configurationSteps: ['For your Posting Period Variant, define the allowed posting period range (From Period, To Period) for each account type.'],
        integrationNotes: 'The "+" entry is a wildcard for all account types. Specific entries for Assets (A), Customers (D), Vendors (K), Materials (M), and G/L (S) override the wildcard.',
        updatesS4HANA: 'The transaction and its purpose are identical in S/4HANA.',
      },
    },
     {
      id: 'l2-9',
      title: 'Define Field Status Variant',
      duration: 15,
      details: {
        tCode: 'OBC4',
        sproPath: 'Financial Accounting > Financial Accounting Global Settings > Ledgers > Fields > Define Field Status Variants',
        definition: 'A Field Status Variant contains multiple Field Status Groups. Each Field Status Group controls which fields are suppressed, displayed, required, or optional during document entry for G/L account line items.',
        purpose: 'To tailor the data entry screens for G/L transactions, making them user-friendly and ensuring all necessary information is captured.',
        configurationSteps: ['Copy a standard variant (e.g., 0001). Within the variant, analyze a Field Status Group (e.g., G001 for general accounts) to see the field controls.'],
        integrationNotes: 'The Field Status Group is assigned to a G/L account in its master record (FS00), linking the account to these screen layout rules.',
        updatesS4HANA: 'This concept remains fundamental and unchanged in S/4HANA.',
      },
    },
    {
      id: 'l2-10',
      title: 'Assign Field Status Variant to Company Code',
      duration: 5,
      details: {
        tCode: 'OBC5',
        sproPath: 'Financial Accounting > Financial Accounting Global Settings > Ledgers > Fields > Assign Company Code to Field Status Variants',
        definition: 'This step links a company code to a Field Status Variant.',
        purpose: 'To ensure that all G/L account postings in that company code follow the field status rules defined in the variant.',
        configurationSteps: ['Assign your 4-character Field Status Variant to your company code.'],
        integrationNotes: 'This is a mandatory assignment for a company code to be transactionally active.',
        updatesS4HANA: 'This assignment logic is unchanged in S/4HANA.',
      },
    },
  ],
  quiz: {
    id: 'fico-q2',
    title: 'Org Structure Quiz',
    questions: [
      { question: 'What transaction is used to open and close posting periods?', options: ['OB29', 'OBC4', 'OB52'], correctAnswer: 2 },
      { question: 'A Field Status Group controls the fields for which part of a document?', options: ['Document Header', 'G/L Account Line Item', 'Vendor Master Record'], correctAnswer: 1 },
      { question: 'In S/4HANA, what is the best practice for internal segment reporting instead of Business Areas?', options: ['Cost Centers', 'Profit Centers and Segments', 'Company Codes'], correctAnswer: 1 },
      { question: 'What transaction code is used to assign a Field Status Variant to a Company Code?', options: ['OB37', 'OBC5', 'OX16'], correctAnswer: 1 },
    ]
  }
};