import type { Chapter } from '../../../types';

export const CHAPTER_4_ACCOUNTS_PAYABLE: Chapter = {
  id: 'ch4',
  title: '4. Account Payable Configurations & Operation',
  lessons: [
    {
      id: 'l4-1',
      title: 'Create Vendor Account Groups',
      duration: 15,
      details: {
        tCode: 'OBD3',
        sproPath: 'Financial Accounting > Accounts Receivable and Accounts Payable > Vendor Accounts > Master Data > Preparations for Creating Vendor Master Data > Define Account Groups with Screen Layout (Vendors)',
        definition: 'Vendor Account Groups classify vendors (e.g., domestic, foreign, one-time). They control the number range and the field status for vendor master records.',
        purpose: 'To organize vendor master data logically and control data entry fields during vendor creation. This ensures different types of vendors have the appropriate data fields and unique number ranges.',
        configurationSteps: ['Define a 4-character key, description, and configure the field status for General, Company Code, and Purchasing data sections.'],
        integrationNotes: 'The field status here controls the fields in the vendor master record, not in transaction posting.',
        updatesS4HANA: 'This configuration is still essential for defining vendor types, but the master data creation itself is now done via the Business Partner (BP) transaction. The Account Group is assigned within the BP role.',
      },
    },
    {
      id: 'l4-2',
      title: 'Create & Assign Number Ranges',
      duration: 10,
      details: {
        tCode: 'XKN1 (Create), OBAS (Assign)',
        sproPath: 'Financial Accounting > Accounts Receivable and Accounts Payable > Vendor Accounts > Master Data > Preparations... > Create Number Ranges... & Assign Number Ranges...',
        definition: 'Define number intervals for unique vendor account numbers and assign them to the vendor account groups.',
        purpose: 'To ensure every vendor master has a unique ID, which can be system-assigned (internal) or user-assigned (external).',
        configurationSteps: ['In XKN1, define a number range interval. In OBAS, assign this range to your Vendor Account Group.'],
        integrationNotes: 'If the number range assigned to a vendor account group in BP CVI configuration is different from the one assigned here, it can lead to synchronization errors.',
        updatesS4HANA: 'This is still required. However, you also need to define number ranges for the Business Partner Grouping and ensure they are aligned (e.g., set to external and synchronized) with the vendor number ranges for smooth master data creation.',
      },
    },
    {
        id: 'l4-3',
        title: 'Create Vendor Master',
        duration: 20,
        details: {
          tCode: 'BP (Business Partner)',
          sproPath: 'N/A',
          definition: 'In S/4HANA, the Business Partner (BP) is the single point of entry for creating vendor master records. Classic transactions like XK01/FK01 are obsolete.',
          purpose: 'To maintain all necessary vendor information (general data, company code data, purchasing data) in one central object. You create a BP and then extend it to the necessary roles, such as "FI Vendor".',
          configurationSteps: ['Go to T-Code BP. Create a new Organization or Person. Fill in General Data. Then, add the "FI Vendor" role and maintain company-code-specific data like the reconciliation account.'],
          integrationNotes: 'The link between the BP and the vendor master is managed through Customer-Vendor Integration (CVI) settings.',
          updatesS4HANA: 'This is a mandatory change. Using T-Code BP for vendor (and customer) creation is a fundamental shift from SAP ECC.',
        },
    },
     {
        id: 'l4-4',
        title: 'Purchase Invoice Posting',
        duration: 15,
        details: {
          tCode: 'FB60 (FI Invoice), MIRO (Logistics Invoice)',
          sproPath: 'N/A',
          definition: 'This is the process of recording a vendor invoice. FB60 is for non-PO invoices (direct to FI), while MIRO is for invoices with reference to a Purchase Order (the integrated logistics process).',
          purpose: 'To create a liability against the vendor and post the expense or asset, initiating the payment process.',
          configurationSteps: ['In FB60, enter vendor, date, amount, G/L account, and cost object. In MIRO, reference the PO number, and the system proposes most of the data.'],
          integrationNotes: 'MIRO is part of the MM module and is tightly integrated with FI. It posts to the GR/IR account and the vendor reconciliation account.',
          updatesS4HANA: 'The transactions are still available. The Fiori app "Create Supplier Invoice" provides a modern, role-based alternative to MIRO.',
        },
    },
    {
        id: 'l4-5',
        title: 'Outgoing Payments',
        duration: 15,
        details: {
          tCode: 'F-53 (Manual Post), F110 (Automatic)',
          sproPath: 'N/A',
          definition: 'This is the process of posting an outgoing payment to a vendor and clearing the corresponding open invoice(s).',
          purpose: 'To record the payment to a vendor, clear the open payable, and update the bank G/L account.',
          configurationSteps: ['In F-53, enter bank data in the header, then the vendor account and amount. Select the open items to be cleared and post.'],
          integrationNotes: 'This process updates the vendor sub-ledger and the general ledger simultaneously.',
          updatesS4HANA: 'F-53 still exists. The Fiori app "Post Outgoing Payments" offers a modern alternative. F110 remains the core for automatic payments.',
        },
    },
    {
        id: 'l4-6',
        title: 'Vendor Credit Memo',
        duration: 10,
        details: {
          tCode: 'FB65',
          sproPath: 'N/A',
          definition: 'A Vendor Credit Memo is posted when a vendor sends a credit note, for example, for returned goods or a price correction.',
          purpose: 'To reduce the amount owed to a vendor. It creates a debit posting on the vendor account.',
          configurationSteps: ['The screen is very similar to FB60, but the posting logic is reversed.'],
          integrationNotes: 'Like invoices, credit memos can also reference a Purchase Order if they are part of the logistics process.',
          updatesS4HANA: 'The transaction is the same. The Fiori app "Create Supplier Invoice" can also be used to post credit memos.',
        },
    },
    {
        id: 'l4-7',
        title: 'Advance Payments (Special G/L)',
        duration: 20,
        details: {
          tCode: 'F-48 (Post Down Payment Request), F-47 (Post Down Payment)',
          sproPath: 'Financial Accounting > Accounts Receivable and Accounts Payable > Business Transactions > Down Payment Made',
          definition: 'Advance payments or down payments to vendors are managed using Special G/L Transactions. These are statistical postings that do not affect the standard vendor reconciliation account but are tracked in a separate special G/L account.',
          purpose: 'To track advance payments made to a vendor before goods or services are received, without distorting the normal payables balance.',
          configurationSteps: ['Configure alternative reconciliation accounts for down payments in T-Code OBYR.'],
          integrationNotes: 'Down payment requests (F-47) are noted items and do not create accounting entries. The actual down payment (F-48) creates the FI posting.',
          updatesS4HANA: 'The process and transactions are still valid. Fiori apps like "Manage Supplier Down Payment Requests" are also available.',
        },
    },
     {
        id: 'l4-8',
        title: 'Terms of Payments',
        duration: 15,
        details: {
          tCode: 'OBB8',
          sproPath: 'Financial Accounting > Accounts Receivable and Accounts Payable > Business Transactions > Outgoing Invoices/Credit Memos > Maintain Terms of Payment',
          definition: 'Payment Terms define the due dates for invoices and any available cash discounts. They can be configured with various rules, such as "3% discount if paid in 10 days, net 30 days".',
          purpose: 'To automate the calculation of invoice due dates and cash discount amounts, which influences the payment process.',
          configurationSteps: ['Define a 4-character key and specify the rules for baseline date calculation, discount percentages, and days.'],
          integrationNotes: 'Payment terms are assigned in the vendor master record and can be changed during invoice entry.',
          updatesS4HANA: 'The configuration remains identical in S/4HANA.',
        },
    },
    {
        id: 'l4-9',
        title: 'Automatic Payment Program (APP)',
        duration: 30,
        details: {
          tCode: 'FBZP (Configuration), F110 (Run)',
          sproPath: 'Financial Accounting > Accounts Receivable and Accounts Payable > Business Transactions > Outgoing Payments > Automatic Outgoing Payments',
          definition: 'APP is a powerful tool that automates the process of making payments to vendors. It selects open invoices due for payment, creates payment documents, and generates payment media (e.g., check file, ACH file).',
          purpose: 'To process vendor payments in bulk, saving significant time and reducing manual errors.',
          configurationSteps: [
              "The configuration in FBZP has 6 steps:",
              "1. <b>All Company Codes:</b> Define sending and paying company codes.",
              "2. <b>Paying Company Codes:</b> Set minimum amounts and forms.",
              "3. <b>Payment Methods in Country:</b> Define payment methods (e.g., check, wire).",
              "4. <b>Payment Methods in Company Code:</b> Assign methods to company codes.",
              "5. <b>Bank Determination:</b> Link payment methods to house banks.",
              "6. <b>House Banks:</b> Set up house banks (T-Code FI12).",
          ],
          integrationNotes: 'The vendor master record must contain the correct payment method and bank details for APP to work correctly.',
          updatesS4HANA: 'FBZP and F110 are still the core transactions. S/4HANA introduces advanced payment management capabilities and Fiori apps like "Manage Automatic Payments" for a more streamlined user experience.',
        },
    },
  ],
  quiz: {
    id: 'fico-q4',
    title: 'Accounts Payable Quiz',
    questions: [
      { question: 'In S/4HANA, which transaction is mandatory for creating a vendor master record?', options: ['XK01', 'FK01', 'BP'], correctAnswer: 2 },
      { question: 'Which transaction is used for the entire configuration of the Automatic Payment Program (APP)?', options: ['F110', 'FBZP', 'OBB8'], correctAnswer: 1 },
      { question: 'Advance payments to vendors are handled through what functionality?', options: ['Standard Postings', 'Recurring Entries', 'Special G/L Transactions'], correctAnswer: 2 },
      { question: 'Which transaction is used for posting a logistics invoice against a Purchase Order?', options: ['FB60', 'F-53', 'MIRO'], correctAnswer: 2 },
    ]
  }
};