import type { Chapter } from '../../../types';

export const CHAPTER_4_PROGRAMMING_BASICS: Chapter = {
  id: 'ch4',
  title: '4. Programming Basics',
  lessons: [
    {
        id: 'l3-1',
        title: 'First ABAP Program & Syntax',
        duration: 15,
        details: {
            tCode: 'SE38',
            sproPath: 'N/A',
            definition: 'An ABAP program is a collection of statements that are executed by the application server. The ABAP Editor (in SE38 or SE80) is the tool used to write code.',
            purpose: 'To create executable reports, function modules, classes, and other development objects.',
            configurationSteps: [
                'Key Syntax Rules:',
                ' - Every statement must end with a period (.).',
                ' - Comments start with an asterisk (*) at the beginning of the line, or a double quote (") anywhere in the line.',
                ' - Keywords are not case-sensitive, but variables are.',
                ' - The `WRITE` statement is used to display output on the screen.',
                ' - Example: `WRITE \'Hello, World!\'.`',
            ],
            integrationNotes: 'Programs are stored in the SAP database and are transportable between systems (Development, QA, Production).',
            updatesS4HANA: 'The core syntax is the same. The modern development environment is ABAP Development Tools (ADT) in Eclipse, which provides a much richer editor with features like code completion and quick fixes.',
        },
    },
    {
        id: 'l3-2',
        title: 'Data Types & Variables',
        duration: 20,
        details: {
            tCode: 'SE38',
            sproPath: 'N/A',
            definition: 'A variable is a placeholder for data. Every variable must have a data type, which defines the kind of data it can hold. ABAP has predefined elementary types and also allows you to use types defined in the ABAP Dictionary.',
            purpose: 'To store and manipulate data within a program.',
            configurationSteps: [
                'Variables are declared using the `DATA` keyword.',
                ' - `DATA gv_name TYPE c LENGTH 20.` (c = Character)',
                ' - `DATA gv_age TYPE i.` (i = Integer)',
                ' - `DATA gv_price TYPE p DECIMALS 2.` (p = Packed Number for currency/quantity)',
                ' - `DATA gv_date TYPE d.` (d = Date)',
                'Constants are declared with `CONSTANTS` and their value cannot be changed.',
                ' - `CONSTANTS gc_pi TYPE p DECIMALS 10 VALUE \'3.1415926535\'.`',
            ],
            integrationNotes: 'You can declare a variable with the same type as a dictionary table field using `DATA gv_kunnr TYPE kna1-kunnr.` This ensures consistency.',
            updatesS4HANA: 'Modern ABAP introduces inline declarations, which are much more convenient: `DATA(lv_text) = \'Hello\'.` The compiler infers the type automatically.',
        },
    },
    {
        id: 'l3-3',
        title: 'Control Structures (IF / CASE)',
        duration: 15,
        details: {
            tCode: 'SE38',
            sproPath: 'N/A',
            definition: 'Control structures allow you to control the flow of program execution based on certain conditions.',
            purpose: 'To make decisions in your code.',
            configurationSteps: [
                '<b>IF...ELSEIF...ELSE...ENDIF.</b>',
                '`IF sy-subrc = 0.`',
                '`  WRITE \'Success\'.`',
                '`ELSEIF sy-subrc = 4.`',
                '`  WRITE \'Not found\'.`',
                '`ELSE.`',
                '`  WRITE \'Error\'.`',
                '`ENDIF.`',
                '<br/>',
                '<b>CASE...WHEN...ENDCASE.</b> (Used when checking one variable against multiple values)',
                '`CASE gv_mode.`',
                '`  WHEN \'A\'.`',
                '`    " Do something for Add`',
                '`  WHEN \'U\'.`',
                '`    " Do something for Update`',
                '`  WHEN OTHERS.`',
                '`    " Handle other cases`',
                '`ENDCASE.`',
            ],
            integrationNotes: '`sy-subrc` is a system variable that holds the return code of many statements (e.g., a database SELECT). 0 usually means success.',
            updatesS4HANA: 'Modern ABAP offers new conditional expressions like `COND` and `SWITCH` that can be used inline and make the code more compact.',
        },
    },
    {
        id: 'l3-4',
        title: 'Loops (DO / WHILE)',
        duration: 15,
        details: {
            tCode: 'SE38',
            sproPath: 'N/A',
            definition: 'Loops are used to execute a block of code repeatedly.',
            purpose: 'To iterate over data or perform an action a specific number of times.',
            configurationSteps: [
                '<b>DO...ENDDO.</b> (Executes a fixed number of times)',
                '`DO 5 TIMES.`',
                '`  WRITE sy-index.` " sy-index is the current loop pass number',
                '`ENDDO.`',
                '<br/>',
                '<b>WHILE...ENDWHILE.</b> (Executes as long as a condition is true)',
                '`DATA lv_counter TYPE i VALUE 5.`',
                '`WHILE lv_counter > 0.`',
                '`  WRITE lv_counter.`',
                '`  lv_counter = lv_counter - 1.`',
                '`ENDWHILE.`',
            ],
            integrationNotes: 'The most common loop in ABAP is `LOOP AT...ENDLOOP`, which is used specifically for iterating over internal tables and will be covered later.',
            updatesS4HANA: 'Modern ABAP introduces iteration expressions like `FOR` that can be used with internal tables for more concise code.',
        },
    },
  ],
  quiz: {
    id: 'abap-q4',
    title: 'Programming Basics Quiz',
    questions: [
      { question: 'Which character is used to end every ABAP statement?', options: ['; (Semicolon)', '. (Period)', ': (Colon)'], correctAnswer: 1 },
      { question: 'Which keyword is used to declare a variable?', options: ['VARIABLE', 'DECLARE', 'DATA'], correctAnswer: 2 },
      { question: 'What is `sy-subrc`?', options: ['A user-defined variable for calculations', 'A system variable that holds the return code of a statement', 'A keyword for starting a subroutine'], correctAnswer: 1 },
      { question: 'In modern ABAP, what is the term for declaring a variable at the point of its first use, like `DATA(lv_text) = ...`?', options: ['Dynamic Declaration', 'Inline Declaration', 'Implicit Declaration'], correctAnswer: 1 },
    ]
  }
};
